import js from "@eslint/js";
import tseslint from "@typescript-eslint/eslint-plugin";
import tsparser from "@typescript-eslint/parser";
import reactPlugin from "eslint-plugin-react";
import reactHooks from "eslint-plugin-react-hooks";
import prettier from "eslint-config-prettier";

export default [
  js.configs.recommended,
  {
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      parser: tsparser,
      parserOptions: {
        ecmaVersion: "latest",
        sourceType: "module",
        ecmaFeatures: { jsx: true },
      },
      globals: {
        window: "readonly",
        document: "readonly",
        console: "readonly",
        process: "readonly",
        __dirname: "readonly",
        __filename: "readonly",
        global: "readonly",
        Buffer: "readonly",
        URL: "readonly",
        URLSearchParams: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        requestAnimationFrame: "readonly",
        cancelAnimationFrame: "readonly",
        performance: "readonly",
        KeyboardEvent: "readonly",
        HTMLElement: "readonly",
        HTMLDivElement: "readonly",
        HTMLInputElement: "readonly",
        HTMLTextAreaElement: "readonly",
        HTMLSelectElement: "readonly",
        HTMLButtonElement: "readonly",
        StorageEvent: "readonly",
        Element: "readonly",
        Node: "readonly",
        // The HTML review path works directly against a parsed document
        // in the report's iframe, so these come up outside React.
        Document: "readonly",
        DOMParser: "readonly",
        DocumentFragment: "readonly",
        Window: "readonly",
        MessageEvent: "readonly",
        Blob: "readonly",
        fetch: "readonly",
        getComputedStyle: "readonly",
        MutationObserver: "readonly",
        MutationRecord: "readonly",
        ScrollLogicalPosition: "readonly",
        Text: "readonly",
        Comment: "readonly",
        Range: "readonly",
        DOMRect: "readonly",
        NodeFilter: "readonly",
        HTMLIFrameElement: "readonly",
        HTMLDialogElement: "readonly",
        ResizeObserver: "readonly",
        Event: "readonly",
        EventTarget: "readonly",
        MouseEvent: "readonly",
        navigator: "readonly",
        crypto: "readonly",
        TextEncoder: "readonly",
        TextDecoder: "readonly",
        CustomEvent: "readonly",
        BeforeUnloadEvent: "readonly",
        KeyboardEventInit: "readonly",
        queueMicrotask: "readonly",
        React: "readonly",
      },
    },
    plugins: {
      "@typescript-eslint": tseslint,
      react: reactPlugin,
      "react-hooks": reactHooks,
    },
    rules: {
      ...tseslint.configs.recommended.rules,
      ...reactPlugin.configs.recommended.rules,
      ...reactHooks.configs.recommended.rules,
      "react/react-in-jsx-scope": "off",
      "react/jsx-uses-react": "off",
      "@typescript-eslint/no-unused-vars": ["warn", { argsIgnorePattern: "^_" }],
    },
    settings: {
      react: { version: "detect" },
    },
  },
  prettier,
  {
    // Node-side scripts run via `node`/`tsx`, not the renderer. They
    // need the Node globals enabled.
    files: ["scripts/**/*.{mjs,js,ts}"],
    languageOptions: {
      globals: {
        process: "readonly",
        console: "readonly",
        Buffer: "readonly",
        __dirname: "readonly",
        __filename: "readonly",
      },
    },
  },
  {
    // The CLI bundle gets its version injected by esbuild (scripts/build-cli.mjs).
    files: ["cli/**/*.ts"],
    languageOptions: {
      globals: {
        __FORGEMARK_VERSION__: "readonly",
      },
    },
  },
  {
    // The renderer uses `fetch` (browser) but eslint's default lib
    // doesn't expose it. Add it alongside the other browser globals.
    files: ["src/**/*.{ts,tsx}"],
    languageOptions: {
      globals: {
        fetch: "readonly",
      },
    },
  },
  {
    ignores: [
      "dist",
      "src/report/report-bridge.built.js",
      "node_modules",
      "src-tauri/target",
      "src-tauri/gen",
      "docs/**",
      // The CLI bundle is generated by scripts/build-cli.mjs from cli/,
      // which is linted; the minified output is not.
      "assets/forgemark-skill/scripts/forgemark.mjs",
      "**/*.config.js",
      "**/*.config.ts",
    ],
  },
];
