// Forgemark's report bridge. Generated by scripts/build-bridge.mjs from
// src/report/bridge-entry.ts; do not edit.
"use strict";
(() => {
  // src/report/decorate.ts
  var OPEN_RE = /^\s*fmc:(\d+)\s*$/;
  var CLOSE_RE = /^\s*\/fmc:(\d+)\s*$/;
  var SVG_NS = "http://www.w3.org/2000/svg";
  var SKIP_PARENTS = /* @__PURE__ */ new Set(["SCRIPT", "STYLE", "TITLE", "TEXTAREA", "NOSCRIPT"]);
  function decorateAnchors(doc, passageIds = /* @__PURE__ */ new Set()) {
    const opens = /* @__PURE__ */ new Map();
    const pairs = [];
    const walker = doc.createTreeWalker(doc, NodeFilter.SHOW_COMMENT);
    const comments = [];
    while (walker.nextNode()) comments.push(walker.currentNode);
    for (const node of comments) {
      const data = node.data;
      const openMatch = OPEN_RE.exec(data);
      if (openMatch) {
        opens.set(Number(openMatch[1]), node);
        continue;
      }
      const closeMatch = CLOSE_RE.exec(data);
      if (closeMatch) {
        const id = Number(closeMatch[1]);
        const open = opens.get(id);
        if (open) {
          pairs.push({ id, open, close: node });
          opens.delete(id);
        }
      }
    }
    const out = [];
    for (const pair of pairs) {
      out.push({
        id: pair.id,
        kind: decoratePair(doc, pair.id, pair.open, pair.close, passageIds.has(pair.id))
      });
    }
    return out;
  }
  function markerPair(doc, id) {
    const walker = doc.createTreeWalker(doc, NodeFilter.SHOW_COMMENT);
    let open = null;
    while (walker.nextNode()) {
      const node = walker.currentNode;
      const o = OPEN_RE.exec(node.data);
      if (o && Number(o[1]) === id) open = node;
      const c = CLOSE_RE.exec(node.data);
      if (c && Number(c[1]) === id && open) return { open, close: node };
    }
    return null;
  }
  function decoratePair(doc, id, open, close, passage) {
    const between = nodesBetween(open, close);
    if (open.parentNode && open.parentNode === close.parentNode) {
      const topLevel = between.filter((n) => n.parentNode === open.parentNode);
      const elements = topLevel.filter((n) => n.nodeType === Node.ELEMENT_NODE);
      const prose = topLevel.filter(
        (n) => n.nodeType === Node.TEXT_NODE && n.data.trim().length > 0
      );
      if (elements.length > 0 && prose.length === 0) {
        for (const el of elements) {
          if (passage) {
            addHost(el, id);
          } else {
            el.setAttribute("data-anchor-id", String(id));
            el.removeAttribute("data-fm-passage-host");
          }
        }
        return "element";
      }
    }
    const texts = between.filter(
      (n) => n.nodeType === Node.TEXT_NODE && n.data.length > 0 && !SKIP_PARENTS.has(n.parentElement?.tagName ?? "") && n.parentElement?.getAttribute("data-anchor-id") !== String(id) && // An HTML <span> inside an <svg> is in the wrong namespace and
      // would not render. Charts are commented on as elements instead.
      n.parentElement?.namespaceURI !== SVG_NS
    );
    for (const text of texts) {
      const span = doc.createElement("span");
      span.setAttribute("data-anchor-id", String(id));
      text.parentNode?.replaceChild(span, text);
      span.appendChild(text);
    }
    return "inline";
  }
  function decoratePassage(doc, id, text) {
    const host = doc.querySelector(`[data-fm-passage-host~="${id}"]`);
    if (!host) return false;
    const wanted = text.replace(/\s+/g, " ").trim();
    const current = Array.from(host.querySelectorAll(`[data-anchor-id="${id}"]`));
    if (current.length > 0) {
      const shown = current.map((el) => el.textContent ?? "").join("").replace(/\s+/g, " ").trim();
      if (shown === wanted) return true;
      for (const el of current) unwrapSpan(el);
    }
    if (wanted.length === 0) return false;
    const whole = textNodesUnder(host).map((n) => n.data).join(" ").replace(/\s+/g, " ").trim();
    if (host.getAttribute("data-anchor-id") === String(id)) {
      if (whole === wanted) return true;
      host.removeAttribute("data-anchor-id");
    }
    if (whole === wanted && !host.hasAttribute("data-anchor-id")) {
      host.setAttribute("data-anchor-id", String(id));
      return true;
    }
    const nodes = textNodesUnder(host);
    let joined = "";
    const starts = [];
    for (const node of nodes) {
      starts.push(joined.length);
      joined += node.data;
    }
    const at = collapsedIndexOf(joined, wanted);
    if (!at) return false;
    const [from, to] = at;
    const spans = [];
    for (let i = 0; i < nodes.length; i++) {
      const nodeStart = starts[i];
      const nodeEnd = nodeStart + nodes[i].data.length;
      if (nodeEnd <= from || nodeStart >= to) continue;
      let node = nodes[i];
      const head = Math.max(0, from - nodeStart);
      const tail = Math.max(0, nodeEnd - to);
      if (head > 0) node = node.splitText(head);
      if (tail > 0) node.splitText(node.data.length - tail);
      if (node.parentElement?.namespaceURI === SVG_NS) continue;
      const span = doc.createElement("span");
      span.setAttribute("data-anchor-id", String(id));
      node.parentNode?.replaceChild(span, node);
      span.appendChild(node);
      spans.push(span);
    }
    return spans.length > 0;
  }
  function collapsedIndexOf(haystack, wanted) {
    const map = [];
    let collapsed = "";
    let pendingSpace = false;
    for (let i = 0; i < haystack.length; i++) {
      const ch = haystack[i];
      if (/\s/.test(ch)) {
        pendingSpace = collapsed.length > 0;
        continue;
      }
      if (pendingSpace) {
        collapsed += " ";
        map.push(i);
        pendingSpace = false;
      }
      collapsed += ch;
      map.push(i);
    }
    const at = collapsed.indexOf(wanted);
    if (at < 0) return null;
    return [map[at], map[at + wanted.length - 1] + 1];
  }
  function textNodesUnder(root) {
    const out = [];
    const walker = root.ownerDocument.createTreeWalker(root, NodeFilter.SHOW_TEXT);
    while (walker.nextNode()) {
      const node = walker.currentNode;
      if (SKIP_PARENTS.has(node.parentElement?.tagName ?? "")) continue;
      if (node.parentElement?.closest("[data-forgemark]")) continue;
      out.push(node);
    }
    return out;
  }
  function addHost(el, id) {
    const ids = (el.getAttribute("data-fm-passage-host") ?? "").split(/\s+/).filter(Boolean);
    if (!ids.includes(String(id))) ids.push(String(id));
    el.setAttribute("data-fm-passage-host", ids.join(" "));
  }
  function unwrapSpan(el) {
    const parent = el.parentNode;
    if (!parent) return;
    while (el.firstChild) parent.insertBefore(el.firstChild, el);
    parent.removeChild(el);
    parent.normalize();
  }
  function removeAnchor(doc, id) {
    const pair = markerPair(doc, id);
    pair?.open.remove();
    pair?.close.remove();
    for (const el of Array.from(doc.querySelectorAll(`[data-anchor-id="${id}"]`))) {
      if (el.tagName === "SPAN" && el.attributes.length === 1) unwrapSpan(el);
      else el.removeAttribute("data-anchor-id");
    }
    for (const el of Array.from(doc.querySelectorAll(".is-focused, .is-hovered, .is-resolved"))) {
      if (!el.hasAttribute("data-anchor-id"))
        el.classList.remove("is-focused", "is-hovered", "is-resolved");
    }
    for (const el of Array.from(doc.querySelectorAll(`[data-fm-passage-host~="${id}"]`))) {
      const rest = (el.getAttribute("data-fm-passage-host") ?? "").split(/\s+/).filter((v) => v && v !== String(id));
      if (rest.length) el.setAttribute("data-fm-passage-host", rest.join(" "));
      else el.removeAttribute("data-fm-passage-host");
    }
  }
  function nodesBetween(start, end) {
    const out = [];
    let node = nextInDocumentOrder(start);
    while (node && node !== end) {
      out.push(node);
      node = nextInDocumentOrder(node);
    }
    return out;
  }
  function nextInDocumentOrder(node) {
    if (node.firstChild) return node.firstChild;
    let current = node;
    while (current) {
      if (current.nextSibling) return current.nextSibling;
      current = current.parentNode;
    }
    return null;
  }
  function applyAnchorState(doc, focusedId, hoveredId, resolvedIds) {
    const all = doc.querySelectorAll("[data-anchor-id]");
    all.forEach((el) => {
      const raw = el.getAttribute("data-anchor-id");
      const id = raw == null ? null : Number(raw);
      el.classList.toggle("is-focused", id === focusedId);
      el.classList.toggle("is-hovered", id === hoveredId);
      el.classList.toggle("is-resolved", id != null && resolvedIds.has(id));
    });
  }
  function anchorElement(doc, id) {
    return doc.querySelector(`[data-anchor-id="${id}"]`);
  }

  // src/report/dom.ts
  var SKIP_CONTENT = /* @__PURE__ */ new Set(["SCRIPT", "STYLE", "TITLE", "TEXTAREA", "NOSCRIPT"]);
  var INJECTED_ATTR = "data-forgemark";
  function walkTextNodes(root) {
    const out = [];
    const visit = (node) => {
      if (node.nodeType === Node.TEXT_NODE) {
        out.push(node);
        return;
      }
      if (node.nodeType === Node.ELEMENT_NODE) {
        const el = node;
        if (SKIP_CONTENT.has(el.tagName) || el.hasAttribute(INJECTED_ATTR)) return;
      }
      for (let child = node.firstChild; child; child = child.nextSibling) visit(child);
    };
    visit(root);
    return out;
  }
  function renderedText(root) {
    return walkTextNodes(root).map((n) => n.data).join("");
  }
  function textIndexOf(root, container, offset) {
    const nodes = walkTextNodes(root);
    if (container.nodeType === Node.TEXT_NODE) {
      let total = 0;
      for (const node of nodes) {
        if (node === container) return total + Math.min(offset, node.data.length);
        total += node.data.length;
      }
      return null;
    }
    const children = Array.from(container.childNodes);
    const target = children[offset];
    if (!target) {
      const inside2 = walkTextNodes(container);
      const last = inside2[inside2.length - 1];
      if (!last) return null;
      const at = textIndexOf(root, last, last.data.length);
      return at;
    }
    const inside = walkTextNodes(target);
    const first = inside[0];
    if (!first) return null;
    return textIndexOf(root, first, 0);
  }
  function describeElement(el) {
    const caption = el.querySelector("figcaption, caption");
    const captionText = caption?.textContent?.trim();
    if (captionText) return collapse(captionText);
    const heading = el.querySelector("th");
    const headingText = heading?.textContent?.trim();
    if (headingText) return collapse(`${el.tagName.toLowerCase()}: ${headingText}`);
    const own = el.textContent?.trim();
    if (own) return collapse(own);
    return el.tagName.toLowerCase();
  }
  function collapse(s, max = 120) {
    const flat = s.replace(/\s+/g, " ").trim();
    return flat.length > max ? flat.slice(0, max - 1).trimEnd() + "\u2026" : flat;
  }

  // src/report/bridge.ts
  var BLOCK_SELECTOR = "figure, table, blockquote, pre, img, video, svg, canvas";
  var BLOCKISH = "p, div, section, article, main, aside, header, footer, nav, li, td, th, tr, h1, h2, h3, h4, h5, h6, figcaption, blockquote, pre, dt, dd";
  function scrollInto(el, block) {
    if (el && typeof el.scrollIntoView === "function") {
      el.scrollIntoView({ block, behavior: "smooth" });
    }
  }
  var ID_RE = /^[A-Za-z][\w-]*$/;
  function installBridge(win, channel) {
    const doc = win.document;
    const captures = /* @__PURE__ */ new Map();
    let captureCount = 0;
    let comments = [];
    let state = { focused: null, hovered: null, resolved: [] };
    let disposed = false;
    const passageIds = () => new Set(comments.filter((c) => c.kind === "passage").map((c) => c.id));
    const decorate = () => {
      decorateAnchors(doc, passageIds());
      for (const c of comments) {
        if (c.kind === "passage" && c.text) decoratePassage(doc, c.id, c.text);
      }
      applyAnchorState(doc, state.focused, state.hovered, new Set(state.resolved));
    };
    const style = doc.createElement("style");
    style.setAttribute("data-forgemark", "anchors");
    const applyTheme = (theme) => {
      doc.documentElement.setAttribute("data-theme", theme.name);
      style.textContent = theme.stylesheet;
      if (!style.isConnected) (doc.head ?? doc.documentElement).appendChild(style);
    };
    const buttons = /* @__PURE__ */ new Map();
    const isHidden = (el) => {
      try {
        const s = win.getComputedStyle(el);
        return s.display === "none" || s.visibility === "hidden";
      } catch {
        return false;
      }
    };
    const offsetBase = () => {
      const body = doc.body;
      if (!body) return { left: 0, top: 0 };
      try {
        if (win.getComputedStyle(body).position !== "static") {
          const r = body.getBoundingClientRect();
          return { left: r.left, top: r.top };
        }
      } catch {
      }
      return { left: -win.scrollX, top: -win.scrollY };
    };
    const refreshBlocks = () => {
      const body = doc.body;
      if (!body) return;
      const all = Array.from(doc.querySelectorAll(BLOCK_SELECTOR)).filter(
        (el) => !el.closest("[data-forgemark]")
      );
      const outermost = all.filter((el) => !el.parentElement?.closest(BLOCK_SELECTOR));
      const live = /* @__PURE__ */ new Set();
      const base = offsetBase();
      const width = doc.documentElement.clientWidth || win.innerWidth;
      for (const el of outermost) {
        if (isHidden(el)) continue;
        let rect;
        try {
          rect = el.getBoundingClientRect();
        } catch {
          continue;
        }
        const laidOut = rect.width > 0 || rect.height > 0;
        if (laidOut && (rect.width < 120 || rect.height < 48)) {
          const button2 = buttons.get(el);
          if (button2) {
            button2.remove();
            buttons.delete(el);
          }
          continue;
        }
        live.add(el);
        let button = buttons.get(el);
        if (!button) {
          button = doc.createElement("button");
          button.type = "button";
          button.setAttribute("data-forgemark", "block");
          button.textContent = "Comment";
          button.addEventListener("click", (e) => {
            e.preventDefault();
            e.stopPropagation();
            sendElementCapture(el);
          });
          body.appendChild(button);
          buttons.set(el, button);
        }
        const label = describeElement(el);
        button.title = `Comment on ${label}`;
        button.setAttribute("aria-label", `Comment on ${label}`);
        const inMargin = rect.right + 96 <= width;
        const left = inMargin ? rect.right + 10 : Math.max(0, rect.right - 6 - 72);
        button.style.left = `${left - base.left}px`;
        button.style.top = `${rect.top + 6 - base.top}px`;
      }
      for (const [el, button] of buttons) {
        if (!live.has(el)) {
          button.remove();
          buttons.delete(el);
        }
      }
    };
    const frameRect = (r) => ({
      left: r.left,
      top: r.top,
      right: r.right,
      bottom: r.bottom
    });
    const containerIds = (node) => {
      const out = [];
      let el = node ? node.nodeType === Node.ELEMENT_NODE ? node : node.parentElement : null;
      while (el && el !== doc.documentElement) {
        const id = el.getAttribute("id");
        if (id && ID_RE.test(id) && !el.hasAttribute("data-forgemark")) out.push(id);
        el = el.parentElement;
      }
      return out;
    };
    const rectOfRange = (range) => {
      try {
        const rects = typeof range.getClientRects === "function" ? range.getClientRects() : null;
        const list = rects && rects.length > 0 ? Array.from(rects) : [range.getBoundingClientRect()];
        const last = list[list.length - 1];
        const highest = list.reduce((a, b) => b.top < a.top ? b : a, list[0]);
        return { left: last.left, top: highest.top, right: last.right, bottom: last.bottom };
      } catch {
        const el = range.commonAncestorContainer.nodeType === Node.ELEMENT_NODE ? range.commonAncestorContainer : range.commonAncestorContainer.parentElement;
        try {
          return frameRect(
            el ? el.getBoundingClientRect() : { left: 0, top: 0, right: 0, bottom: 0 }
          );
        } catch {
          return { left: 0, top: 0, right: 0, bottom: 0 };
        }
      }
    };
    const overlappingAnchor = (range) => {
      const container = range.commonAncestorContainer.nodeType === Node.ELEMENT_NODE ? range.commonAncestorContainer : range.commonAncestorContainer.parentElement;
      if (!container) return null;
      const enclosing = container.closest("[data-anchor-id]");
      if (enclosing) {
        const id = Number(enclosing.getAttribute("data-anchor-id"));
        if (Number.isFinite(id)) return id;
      }
      for (const el of Array.from(container.querySelectorAll("[data-anchor-id]"))) {
        if (range.intersectsNode(el)) {
          const id = Number(el.getAttribute("data-anchor-id"));
          if (Number.isFinite(id)) return id;
        }
      }
      return null;
    };
    const anchorIdOf = (node) => {
      const el = node ? node.nodeType === Node.ELEMENT_NODE ? node : node.parentElement : null;
      const raw = el?.closest("[data-anchor-id]")?.getAttribute("data-anchor-id");
      const id = raw == null ? NaN : Number(raw);
      return Number.isFinite(id) ? id : null;
    };
    const newToken = () => `c${++captureCount}`;
    const contextAround = (range) => {
      const nodes = walkTextNodes(doc);
      const blockOf = (n) => n.parentElement?.closest(BLOCKISH) ?? null;
      const start = textIndexOf(doc, range.startContainer, range.startOffset);
      const end = textIndexOf(doc, range.endContainer, range.endOffset);
      if (start == null || end == null) return { before: "", after: "" };
      let at = 0;
      let before = "";
      let after = "";
      let prev = null;
      for (const node of nodes) {
        const gap = prev && blockOf(prev) !== blockOf(node) ? " " : "";
        const from = at;
        const to = at + node.data.length;
        if (from < start)
          before += gap + node.data.slice(0, Math.min(node.data.length, start - from));
        if (to > end) after += (from >= end ? gap : "") + node.data.slice(Math.max(0, end - from));
        at = to;
        prev = node;
      }
      return {
        before: before.replace(/\s+/g, " ").trimStart().slice(-80).trim(),
        after: after.replace(/\s+/g, " ").trimEnd().slice(0, 80).trim()
      };
    };
    const captureSelection = () => {
      const selection = doc.getSelection();
      if (!selection || selection.rangeCount === 0 || selection.isCollapsed) return null;
      const range = selection.getRangeAt(0);
      const text = selection.toString().replace(/\s+/g, " ").trim();
      if (text.length === 0) return null;
      const { before, after } = contextAround(range);
      const token = newToken();
      captures.set(token, { range: range.cloneRange() });
      if (captures.size > 20) captures.delete(captures.keys().next().value);
      return {
        token,
        text,
        contextBefore: before,
        contextAfter: after,
        containerIds: containerIds(range.commonAncestorContainer),
        overlappingAnchorId: overlappingAnchor(range),
        rect: rectOfRange(range)
      };
    };
    const sendElementCapture = (el) => {
      const token = newToken();
      captures.set(token, { el });
      const existing = el.closest("[data-anchor-id]");
      const existingId = existing ? Number(existing.getAttribute("data-anchor-id")) : NaN;
      const ownId = el.getAttribute("id");
      let rect;
      try {
        rect = frameRect(el.getBoundingClientRect());
      } catch {
        rect = { left: 0, top: 0, right: 0, bottom: 0 };
      }
      const element = {
        token,
        tag: el.tagName.toLowerCase(),
        description: describeElement(el),
        elementId: ownId && ID_RE.test(ownId) ? ownId : null,
        containerIds: containerIds(el.parentElement),
        textHead: renderedText(el).replace(/\s+/g, " ").trim().slice(0, 60),
        existingAnchorId: Number.isFinite(existingId) ? existingId : null,
        rect
      };
      channel.send({ type: "elementCapture", element });
    };
    let lastSelectionKey = "";
    let lastCaretAnchor = null;
    const reportSelection = () => {
      if (disposed) return;
      const selection = doc.getSelection();
      const caretAnchor = anchorIdOf(selection?.anchorNode ?? null);
      if (caretAnchor == null) {
        lastCaretAnchor = null;
      } else if (caretAnchor !== lastCaretAnchor) {
        lastCaretAnchor = caretAnchor;
        channel.send({ type: "anchorClick", id: caretAnchor });
      }
      if (!selection || selection.rangeCount === 0 || selection.isCollapsed) {
        if (lastSelectionKey !== "") {
          lastSelectionKey = "";
          channel.send({ type: "selection", selection: null });
        }
        return;
      }
      const range = selection.getRangeAt(0);
      const box = rectOfRange(range);
      const key = [
        range.startOffset,
        range.endOffset,
        selection.toString().length,
        Math.round(box.top),
        Math.round(box.left)
      ].join(":");
      if (key === lastSelectionKey) return;
      lastSelectionKey = key;
      channel.send({ type: "selection", selection: captureSelection() });
    };
    let remembered = null;
    const rememberSelection = () => {
      reportSelection();
      const selection = doc.getSelection();
      if (!selection || selection.rangeCount === 0 || selection.isCollapsed) return;
      if (selection.toString().trim().length === 0) return;
      remembered = selection.getRangeAt(0).cloneRange();
    };
    const boxesFor = (range) => {
      try {
        if (typeof range.getClientRects === "function") {
          const rects = range.getClientRects();
          if (rects.length > 0) return Array.from(rects);
        }
      } catch {
      }
      try {
        if (typeof range.getBoundingClientRect === "function") {
          return [range.getBoundingClientRect()];
        }
      } catch {
      }
      const node = range.commonAncestorContainer;
      const el = node.nodeType === Node.ELEMENT_NODE ? node : node.parentElement;
      try {
        return el ? [el.getBoundingClientRect()] : [];
      } catch {
        return [];
      }
    };
    const rangeContainsPoint = (range, x, y) => boxesFor(range).some(
      (r) => x >= r.left - 2 && x <= r.right + 2 && y >= r.top - 2 && y <= r.bottom + 2
    );
    const onClick = (e) => {
      const target = e.target;
      if (target?.closest?.("[data-forgemark]")) return;
      const link = target?.closest?.("a[href]");
      if (link) {
        e.preventDefault();
        const href = link.getAttribute("href") ?? "";
        if (href.startsWith("#")) {
          const id = decodeURIComponent(href.slice(1));
          const el = doc.getElementById(id) ?? Array.from(doc.querySelectorAll("a[name]")).find((a) => a.getAttribute("name") === id) ?? null;
          scrollInto(el, "start");
        } else {
          channel.send({ type: "link", href });
        }
        return;
      }
      channel.send({ type: "anchorClick", id: anchorIdOf(e.target) });
    };
    const onMouseOver = (e) => {
      const id = anchorIdOf(e.target);
      if (id !== null) channel.send({ type: "anchorHover", id });
    };
    const onMouseOut = (e) => {
      if (anchorIdOf(e.target) !== null) channel.send({ type: "anchorHover", id: null });
    };
    const onContextMenu = (e) => {
      e.preventDefault();
      const selection = doc.getSelection();
      const live = selection && !selection.isCollapsed && selection.toString().trim().length > 0;
      if (!live) {
        if (!remembered || !selection) return;
        try {
          if (!rangeContainsPoint(remembered, e.clientX, e.clientY)) return;
          selection.removeAllRanges();
          selection.addRange(remembered);
        } catch {
          return;
        }
        if (selection.toString().trim().length === 0) return;
      }
      reportSelection();
      channel.send({ type: "contextmenu", x: e.clientX, y: e.clientY });
    };
    let refreshTimer = null;
    const scheduleRefresh = () => {
      if (refreshTimer != null) return;
      refreshTimer = win.setTimeout(() => {
        refreshTimer = null;
        if (disposed) return;
        decorate();
        refreshBlocks();
      }, 60);
    };
    doc.addEventListener("click", onClick);
    doc.addEventListener("mouseover", onMouseOver);
    doc.addEventListener("mouseout", onMouseOut);
    doc.addEventListener("contextmenu", onContextMenu);
    doc.addEventListener("mouseup", rememberSelection);
    doc.addEventListener("keyup", rememberSelection);
    doc.addEventListener("selectionchange", rememberSelection);
    win.addEventListener("scroll", reportSelection, { passive: true });
    win.addEventListener("resize", scheduleRefresh);
    const poll = win.setInterval(reportSelection, 200);
    const Observer = win.MutationObserver;
    const observer = Observer ? new Observer((records) => {
      if (records.every((r) => isOurs(r.target))) return;
      scheduleRefresh();
    }) : null;
    const isOurs = (node) => {
      const el = node.nodeType === Node.ELEMENT_NODE ? node : node.parentElement;
      return !!el?.closest?.("[data-forgemark], span[data-anchor-id]");
    };
    observer?.observe(doc.documentElement, { childList: true, subtree: true, characterData: true });
    const wrap = (token, id, kind, text, selector) => {
      const capture = captures.get(token);
      if (!capture) return;
      if (!comments.some((c) => c.id === id)) comments = [...comments, { id, kind, text }];
      const open = doc.createComment(` fmc:${id} `);
      const close = doc.createComment(` /fmc:${id} `);
      let host = null;
      if (kind === "passage" && selector) {
        try {
          host = doc.querySelector(selector);
        } catch {
          host = null;
        }
      }
      if (host) {
        host.parentNode?.insertBefore(open, host);
        host.parentNode?.insertBefore(close, host.nextSibling);
      } else if (capture.el) {
        const el = capture.el;
        el.parentNode?.insertBefore(open, el);
        el.parentNode?.insertBefore(close, el.nextSibling);
      } else if (capture.range) {
        const range = capture.range;
        const end = range.cloneRange();
        end.collapse(false);
        end.insertNode(close);
        const start = range.cloneRange();
        start.collapse(true);
        start.insertNode(open);
      }
      captures.delete(token);
      decorate();
      refreshBlocks();
      lastSelectionKey = "";
      reportSelection();
    };
    const onMessage = (message) => {
      if (disposed) return;
      switch (message.type) {
        case "init":
          applyTheme(message.theme);
          state = message.state;
          comments = message.comments;
          decorate();
          refreshBlocks();
          break;
        case "theme":
          applyTheme(message.theme);
          break;
        case "state":
          state = message.state;
          applyAnchorState(doc, state.focused, state.hovered, new Set(state.resolved));
          break;
        case "comments":
          comments = message.comments;
          decorate();
          break;
        case "wrap":
          wrap(message.token, message.id, message.kind, message.text, message.selector);
          break;
        case "unwrap":
          removeAnchor(doc, message.id);
          lastSelectionKey = "";
          reportSelection();
          break;
        case "scrollTo":
          scrollInto(
            anchorElement(doc, message.id) ?? doc.querySelector(`[data-fm-passage-host~="${message.id}"]`),
            "center"
          );
          break;
        case "scrollToFragment":
          scrollInto(doc.getElementById(message.id), "start");
          break;
      }
    };
    const offMessage = channel.onMessage(onMessage);
    channel.send({ type: "ready" });
    void markerPair;
    return () => {
      disposed = true;
      offMessage();
      win.clearInterval(poll);
      if (refreshTimer != null) win.clearTimeout(refreshTimer);
      observer?.disconnect();
      doc.removeEventListener("click", onClick);
      doc.removeEventListener("mouseover", onMouseOver);
      doc.removeEventListener("mouseout", onMouseOut);
      doc.removeEventListener("contextmenu", onContextMenu);
      doc.removeEventListener("mouseup", rememberSelection);
      doc.removeEventListener("keyup", rememberSelection);
      doc.removeEventListener("selectionchange", rememberSelection);
      win.removeEventListener("scroll", reportSelection);
      win.removeEventListener("resize", scheduleRefresh);
      for (const button of buttons.values()) button.remove();
      buttons.clear();
      style.remove();
    };
  }
  function parentChannel(win) {
    return {
      send(message) {
        win.parent.postMessage(message, "*");
      },
      onMessage(listener) {
        const handler = (e) => {
          if (e.source !== win.parent) return;
          if (!e.data || typeof e.data !== "object" || typeof e.data.type !== "string") return;
          listener(e.data);
        };
        win.addEventListener("message", handler);
        return () => win.removeEventListener("message", handler);
      }
    };
  }

  // src/report/bridge-entry.ts
  if (typeof window !== "undefined" && window.parent !== window) {
    const start = () => installBridge(window, parentChannel(window));
    if (document.readyState === "loading") {
      document.addEventListener("DOMContentLoaded", start, { once: true });
    } else {
      start();
    }
  }
})();
