#!/usr/bin/env node
// Bundle the report bridge — the script Forgemark injects into every
// HTML report — into one plain file the app embeds as text.
//
// `src/report/bridge-entry.ts` is compiled by esbuild into
// `src/report/report-bridge.built.js`: an IIFE with no imports, so it
// runs inside a report whatever the report is. The app reads it with a
// `?raw` import and splices it into the report before the report is
// served. The file is committed, so `tauri dev` and a fresh checkout
// have it; a unit test rebuilds it and fails when it is stale, as with
// the CLI bundle.

import { build } from "esbuild";
import { readFileSync } from "node:fs";
import { resolve, dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
export const BRIDGE_ENTRY = join(ROOT, "src", "report", "bridge-entry.ts");
export const BRIDGE_OUT = join(ROOT, "src", "report", "report-bridge.built.js");

export async function buildBridge({ outfile = BRIDGE_OUT, write = true } = {}) {
  return build({
    entryPoints: [BRIDGE_ENTRY],
    outfile,
    bundle: true,
    write,
    platform: "browser",
    format: "iife",
    target: "es2020",
    minify: false,
    legalComments: "none",
    logLevel: "silent",
    banner: {
      js:
        "// Forgemark's report bridge. Generated by scripts/build-bridge.mjs from\n" +
        "// src/report/bridge-entry.ts; do not edit.",
    },
  });
}

const invokedDirectly =
  process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (invokedDirectly) {
  buildBridge()
    .then(() => {
      const bytes = readFileSync(BRIDGE_OUT).length;
      console.log(`Built report bridge (${bytes.toLocaleString()} B): ${BRIDGE_OUT}`);
    })
    .catch((err) => {
      console.error(err);
      process.exit(1);
    });
}
