#!/usr/bin/env node
// Bundle the forgemark CLI into the single file the skill ships.
//
// `cli/main.ts` and the app's format layer are compiled by esbuild into
// `assets/forgemark-skill/scripts/forgemark.mjs`: one ESM file, no
// dependencies, runnable by any Node 18+. The bundle is committed, so an
// agent that installs the skill has the tool without a build step; a
// unit test rebuilds it and fails when the committed file is stale, the
// same way skill-bundle.test.ts guards the zip.
//
// Determinism matters because that test compares bytes: esbuild is
// deterministic for a given input and version, the version is pinned by
// the lockfile, and nothing time- or path-dependent is embedded.

import { build } from "esbuild";
import { readFileSync } from "node:fs";
import { resolve, dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
export const CLI_ENTRY = join(ROOT, "cli", "main.ts");
export const CLI_OUT = join(ROOT, "assets", "forgemark-skill", "scripts", "forgemark.mjs");

export async function buildCli({ outfile = CLI_OUT, write = true } = {}) {
  const { version } = JSON.parse(readFileSync(join(ROOT, "package.json"), "utf8"));
  const result = await build({
    entryPoints: [CLI_ENTRY],
    outfile,
    bundle: true,
    write,
    platform: "node",
    format: "esm",
    target: "node18",
    minify: true,
    legalComments: "none",
    logLevel: "silent",
    define: { __FORGEMARK_VERSION__: JSON.stringify(version) },
    // esbuild keeps the entry file's `#!/usr/bin/env node` line first;
    // the banner goes directly under it. The `createRequire` line is the
    // standard shim for bundling CommonJS dependencies (the `yaml`
    // parser calls `require("process")`) into an ES module.
    banner: {
      js:
        `// forgemark ${version} — the Forgemark review-comment CLI. Generated by scripts/build-cli.mjs;\n` +
        `// do not edit. Run with \`node forgemark.mjs --help\`.\n` +
        `import { createRequire as __createRequire } from "node:module";\n` +
        `const require = __createRequire(import.meta.url);`,
    },
  });
  return result;
}

const invokedDirectly =
  process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (invokedDirectly) {
  buildCli()
    .then(() => {
      const bytes = readFileSync(CLI_OUT).length;
      console.log(`Built CLI bundle (${bytes.toLocaleString()} B): ${CLI_OUT}`);
    })
    .catch((err) => {
      console.error(err);
      process.exit(1);
    });
}
